### PR TITLE
feat(select): fix select virtualization, configuring popup width

### LINKED ISSUE #763: Virtualize select options
## The feature or bug you are proposing

I need to display thousands menu items in the select, each menu item needs to dynamically load a different icon. The current Select component does not let me implement this in a way that is productive without freezing the browser as soon as you click the select.

## A snippet of code for replicating the issue or showing the proposal usage if applicable

Attempting to see how the select behaves when using antd `optionRender`, I've prepared a story as such:

```ts
export const LotsOfOptions: Story = {
  args: {
    options: new Array(2000).fill('option')
      .map((val, i) => ({ label: `${val} ${i}`, value: i })),
    optionRender: (option) => {
      console.log('render', option)
      return <strong>{option.label}</strong>
    },
  },
}
```
however as soon as I open the select

immagine

## The expected result for your bug

virtualization to happen and the render function to be invoked at need

### PR DESCRIPTION
**Pull request by davidebianchi**
### Description

In this PR, resolve issues when the popup content is longer than the width.

Also, resolves #763 using select virtualization by default.

### Addressed issue

Resolves #763

### [IMPORTANT] PR Checklist

- [x] I am aware of standards and conventions adopted in this repository, defined in the [CONTRIBUTING.md file](https://github.com/mia-platform/design-system/blob/main/CONTRIBUTING.md)

#### PR conventions

Please make sure your PR complies with the following rules before submitting it.

- [x] PR title follows the `<type>(<scope>): <subject>` structure
- [x] The PR has been labeled according to the type of changes (e.g. enhancement, new component, bug).

    > **NOTE**  
    > Some labels are used to generate release note entries: you can find the complete mapping between PR labels and release note categories [here](https://github.com/mia-platform/design-system/blob/main/.github/release.yml).  
    For a more detailed overview of PR labels, please refer to the [dedicated CONTRIBUTING section](https://github.com/mia-platform/design-system/blob/main/CONTRIBUTING.md#pull-request-labels).

#### Additional code checks

Based on your changes, some of these checks may not apply. Please make sure to check the relevant items in the list.

- [ ] Changes are covered by tests 
- [x] Changes to components are accessible and documented in the Storybook
- [x] Typings have been updated
- [ ] New components are exported from the `src/index.ts` file
- [ ] New files include the Apache 2.0 License disclaimer
- [x] The browser console does not contain errors

### CODE REVIEW

File: src/components/Input/InputAddon.tsx [hunk 1]
```diff
@@ -79,6 +79,7 @@ export const InputAddon = ({
         <Select
           isDisabled={isDisabled}
           isFullWidth={false}
+          popupMatchSelectWidth={false}
```
Comment (Danielecina) [inline src/components/Input/InputAddon.tsx:82]: can you add to the boolean props the is, has or can prefix?

Comment (davidebianchi) [reply src/components/Input/InputAddon.tsx:82]: Is a bool or number props, not only boolean. Is it needed also in this cases the prefix? Could be maybe misleading?

Comment (davidebianchi) [reply src/components/Input/InputAddon.tsx:82]: If needed, it is ok also should? So, `shouldPopupMatchSelectWidth` would be ok?

File: src/components/Select/props.ts [hunk 2]
```diff
@@ -135,4 +135,11 @@ export type SelectProps<ValueType = unknown> = BaseInputProps & {
    * Customize the rendering of the dropdown.
    */
   dropdownRender?: (menu: ReactNode) => ReactElement
+
+  /**
+   * Determine whether the popup menu and the select input are the same width.
+   * Default set min-width same as input. Will ignore when value less than select width.
+   * false will disable virtual scroll
+   */
```
Comment (ThisIsDemetrio) [inline src/components/Select/props.ts:143]: I leave here a couple of suggestions on the jsdoc

```suggestion
  /**
   * Determine whether the popup menu and the select input should have the same width.
   * Default set `min-width` of the popup to match the input. 
   * This is ignored when the value is less than the select input's width.
   * Setting this to `false` will disable the virtual scroll
   */
```

File: src/components/Input/InputAddon.tsx (hunk 1 above)
Comment (Danielecina) [reply src/components/Input/InputAddon.tsx:82]: mmm so you can use a static width or a general true width. 
In this case I think the name may be fine as you propose. 
Are you sure it works? Because I remember the width is set by the css as “unset” to avoid automatic inheritance. if worts for me is approved

File: src/components/Select/Select.tsx [hunk 3]
```diff
@@ -122,7 +123,7 @@ export const Select = <ValueType, >(
       optionRender={optionRender}
       options={options}
       placeholder={placeholder}
-      popupMatchSelectWidth={false}
+      popupMatchSelectWidth={popupMatchSelectWidth}
```
Comment (fredmaggiowski) [inline src/components/Select/Select.tsx:126]: is this a boolean prop? it's name should start with a verb such as `shouldPopupMatchSelectWidth` or `mustMatchPopupSelectWidth`

**Review by Danielecina — DISMISSED** [review]

File: src/components/Select/Select.tsx (hunk 3 above)
Comment (Danielecina) [reply src/components/Select/Select.tsx:126]: https://github.com/mia-platform/design-system/pull/938#discussion_r2077034626

**Review by fredmaggiowski — APPROVED** [review]
LGTM
